app:
  env: "development"

server:
  TCP:
    Active: true
    Address: ":1869"
  UDP:
    Active: true
    Address: ":1869"
  HTTP:
    Active: true
    Address: ":1969"

log:
  path: "./storage/logs/"
